### ISSUE TITLE
Storage Class for Snapshot Volume failed because Kubernetes 1.30 is not supported

### ISSUE THREAD

**Issue by lionelmace** [lionelmace/kasten-on-iks#1]
Storage Class for Snapshot Volume failed because Kubernetes 1.30 is not supported

![image](https://github.com/user-attachments/assets/28ca44ba-e086-4efe-a363-044dd88f0dda)

**Comment by lionelmace** [comment]
Will test with IKS 1.29
https://github.com/lionelmace/kasten-on-iks/commit/7567dc5505ea7f78d3b478251c77f41213f03a32

**Comment by cpouthier** [comment]
Kubernetes 1.30 is not supported yet, see: https://docs.kasten.io/latest/operating/support.html#supported-kubernetes-versions

**Comment by lionelmace** [comment]
Thank you @cpouthier
